# Generated by Django 2.0.5 on 2018-06-19 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_auto_20180617_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='dcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dcard', to='bank.CrashCard'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='scard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='scard', to='bank.CrashCard'),
        ),
    ]
